stages:
  - test
  - deploy

variables:
  APP_ENV: testing

before_script:
  - echo "Start CI/CD"

# ========================
# TESTING
# ========================
test_job:
  stage: test
  image: php:8.4-cli
  script:
    - echo "Run PHPUnit"
    - ./vendor/bin/phpunit
    # contoh Laravel:
    # - composer install
    # - php artisan test

# ========================
# DEPLOY
# ========================
deploy:
  stage: deploy
  image: php:8.4-cli

  before_script:
    - apt-get update && apt-get install -y git unzip openssh-client
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install

    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 192.168.56.102 >> ~/.ssh/known_hosts

  script:
    - php vendor/bin/envoy run deploy --branch=$CI_COMMIT_REF_NAME