stages:
  - test
  - deploy

variables:
  APP_ENV: testing

before_script:
  - echo "Start CI/CD"

# ========================
# TESTING
# ========================
test_job:
  stage: test
  script:
    - echo "Run PHPUnit"
    - ./vendor/bin/phpunit
    # Laravel: composer install + php artisan test
    # - composer install --no-interaction --prefer-dist
    # - php artisan test

# ========================
# DEPLOY
# ========================
deploy:
  stage: deploy
  script:
    # Pastikan PHP, Composer, Git sudah terinstall di server
    - echo "Deploying to server..."
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 192.168.56.102 >> ~/.ssh/known_hosts
    - php vendor/bin/envoy run deploy --branch=$CI_COMMIT_REF_NAME